export const GEAR_ITEM_OPTIONS = ['Boots', 'Gloves', 'Goggles', 'Helmet', 'Jersey', 'Pants', 'Socks', 'Protection', 'Gear Combo'];
export const GEAR_CONDITION_OPTIONS = ['New - Original Packaging', 'Lightly Used', 'Used - Good condition', 'Used'];
export const GEAR_BRAND_OPTIONS = [
  'Fox Racing',
  'Alpinestars',
  'Thor MX',
  "O'Neal",
  'Shift MX',
  'Leatt',
  'Bell Helmets',
  'Shoei',
  'Arai',
  'Gaerne',
  'Sidi',
  'Fly Racing',
  'Answer Racing',
  'Troy Lee Designs',
  'EVS Sports',
  '6D Helmets',
  'Scott Sports',
  'Atlas Brace',
  'Wiseco',
  'Pro Circuit',
  'FMF Racing',
  'Renthal',
  'Moose Racing',
  'Polisport',
  'Acerbis',
  'Boyesen',
  'Twin Air',
  'Hinson',
  'Works Connection',
  'AFAM',
  'Sunstar',
  'Excel Rims',
  'D.I.D Chains',
  'Showa',
  'KYB',
  'Ohlins',
  'NGK',
  'Motul',
  'Bel-Ray',
  'Alias MX',
];

export const DIRT_BIKE_CATEGORIES = {
  Accessories: [
    'Cleaning Supplies',
    'Fluids & Lubrication',
    'Fuel Jugs & Accessories',
    'Garage Mats',
    'Hydration Packs',
    'Luggage & Bags',
    'Nutrition & Hydration',
    'Owner & Service Manuals',
    'Ramps & Stands',
    'Tie Downs & Straps',
    'Tools & Maintenance',
    'Watches & Wearables',
  ],
  Parts: [
    'Bars & Controls',
    'Body Parts & Accessories',
    'Bolts & Hardware',
    'Brakes',
    'Cooling Systems',
    'Drive',
    'Electrical',
    'Engine',
    'Exhaust',
    'Foot Controls',
    'Fuel System',
    'Intake',
    'Lighting',
    'Suspension',
    'Wheels and Tyres',
  ],
  Gear: GEAR_ITEM_OPTIONS,
};

export const ACCESSORIES_SUBCATEGORIES = DIRT_BIKE_CATEGORIES.Accessories;
export const PARTS_SUBCATEGORIES = DIRT_BIKE_CATEGORIES.Parts;
export const GEAR_SUBCATEGORIES = DIRT_BIKE_CATEGORIES.Gear;
